# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.7.1
      - image: circleci/postgres:12-ram
        environment:
          POSTGRES_USER: testing
          POSTGRES_DB: testing
          POSTGRES_HOST_AUTH_METHOD: trust

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install clj-kondo
          command: |
            curl -sLO https://raw.githubusercontent.com/borkdude/clj-kondo/master/script/install-clj-kondo
            chmod +x install-clj-kondo
            ./install-clj-kondo --dir ~/repo

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: ~/repo/clj-kondo --lint src test

      - run: lein kibit src test

      - run: lein bikeshed

      - run: lein check-namespace-decls

      - run: lein test

      - run: CLOVERAGE_VERSION=1.1.2 lein cloverage --codecov --ns-exclude-regex "wheel-of-misfortune.repositories.scenarios.models"

      - codecov/upload:
          file: ~/repo/target/coverage/codecov.json
